excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://paxbellum.github.io
title: paxbellum
tagline: A log of everyday life
description: All the stuff nobody cares about, not even me. 
paginate: 5